### ISSUE TITLE
I'm little confused  help ! I just this to fix

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/arrrgenes-treasure-tours#1]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/55094325/79339768-579ab500-7ef7-11ea-9b71-1a031512c7ce.png">
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) your `<main>` should start after you close your `<header>` - that first issue is because you have your role=banner inside of your role=main, which shouldnt be happening

2) you're going to have to add a background-color to your .banner. This is because if for some reason the background image you have on your banner doesn't load, then its not just white text on a white background:

.banner {
  min-height: 16em;
  background-color: #704c2a;
  color: #fff;
}

**Comment by Samirahajiragab** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/55094325/79618195-6344d200-80d7-11ea-802a-fc565728daf0.png">
@mackenzierose
Thank so much for help me!

**Comment by MacKenzieRose** [comment]
I'm not seeing the first two errors on my end, so I'm assuming you fixed those.

The other error is because you haven't defined an `outline color` anywhere in your CSS; do that, and if it has a lot of contrast with the background (which often means using black or white), the error should resolve itself.

Let me know if that helps :)
